
server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gpcDb
    username: usr_gpc
    password: gpc@2021
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.show_sql: true
      hibernate.use_sql_comments: true
      hibernate.format_sql: true
      hibernate.type: trace
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

mq:
  exchange:
    name: Machines
  queue:
    name: RESULTADO_DAS_PAUTAS



schedule:
  resultado-pauta: 0 0/1 * * * *

