
server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://ec2-18-232-254-253.compute-1.amazonaws.com:5432/dbk96134uvcs69
    username: kpmzujmcfildus
    password: 67a831212cd98fd0172566754866656ff92be80447bd04bd20f1376e865790ef
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.show_sql: true
      hibernate.use_sql_comments: true
      hibernate.format_sql: true
      hibernate.type: trace
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

  rabbitmq:
    host: amqps://fnwskuow:RuJWGWbEz6d3pfmhZexqARkHSExCyF9y@owl.rmq.cloudamqp.com/fnwskuow
    port: 5672
    username: fnwskuow
    password: RuJWGWbEz6d3pfmhZexqARkHSExCyF9y

  flyway:
    enabled: true
    schemas: jovem
    check-location: false
    locations: db/migration
    url: jdbc:postgresql://ec2-18-232-254-253.compute-1.amazonaws.com:5432/dbk96134uvcs69
    username: kpmzujmcfildus
    password: 67a831212cd98fd0172566754866656ff92be80447bd04bd20f1376e865790ef
    baseline-on-migrate: true

mq:
  exchange:
    name: Machines
  queue:
    name: RESULTADO_DAS_PAUTAS



schedule:
  resultado-pauta: 0 0/1 * * * *

